version: '3'
services:
  client:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - .:/app
  client_tests:
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - /app/node_modules
      - .:/app
    command: ['npm', 'run', 'test']
