version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=springEventsDb
    ports:
    - '5432:5432'
  events:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
    - 'postgres'
