version: '3'
services:
  events-db:
    image: "postgres:10"
  events:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    ports:
    - '9090:9090'
    depends_on:
    - 'events-db'
