version: '3.3'

services:
  scg:
    build:
      context: ./backend/gateway
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    depends_on:
    - eureka

  eureka:
    build:
      context: ./backend/eureka
      dockerfile: Dockerfile
    ports:
    - "8761:8761"

#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile

  bookings-postgres:
    image: "postgres:10"

  movies-postgres:
    image: "postgres:10"

  venues-postgres:
    image: "postgres:10"

  events-postgres:
    image: "postgres:10"

  payment-postgres:
    image: "postgres:10"

  bookings:
    build:
      context: ./backend/booking
      dockerfile: Dockerfile
    depends_on:
    - scg
    - bookings-postgres

  payment:
    build:
      context: ./backend/payment
      dockerfile: Dockerfile
    depends_on:
    - scg
    - payment-postgres

  venues_0:
    build:
      context: ./backend/venues
      dockerfile: Dockerfile
    depends_on:
    - scg
    - venues-postgres

  venues_1:
    build:
      context: ./backend/venues
      dockerfile: Dockerfile
    depends_on:
    - scg
    - venues-postgres

  movies:
    build:
      context: ./backend/movies
      dockerfile: Dockerfile
    depends_on:
    - scg
    - movies-postgres

  events:
    build:
      context: ./backend/events
      dockerfile: Dockerfile
    depends_on:
    - scg
    - events-postgres