version: '3.3'

services:
  scg:
    build:
      context: ./backend/gateway
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    depends_on:
    - eureka

  eureka:
    build:
      context: ./backend/eureka
      dockerfile: Dockerfile
    ports:
    - "8761:8761"

#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile

  postgres:
    image: "postgres:10"

  movies-postgres:
    image: "postgres:10"

  venues-postgres:
    image: "postgres:10"

  service:
    build:
      context: ./backend/booking
      dockerfile: Dockerfile
    depends_on:
    - scg
    - postgres

  venues:
    build:
      context: ./backend/venues
      dockerfile: Dockerfile
    depends_on:
    - scg
    - venues-postgres

  movies:
    build:
      context: ./backend/movies
      dockerfile: Dockerfile
    depends_on:
    - scg
    - movies-postgres