version: '3.3'
services:
  #### DATABASE ####
  auth-db:
    image: 'postgres:latest'
  payment-db:
    image: 'postgres:latest'
  movies-db:
    image: 'postgres:latest'
  venues-db:
    image: 'postgres:latest'
  booking-db:
    image: 'postgres:latest'
  events-db:
    image: 'postgres:latest'

  #### RABBITMQ ####
  rabbitmq:
    image: "rabbitmq:3"

  #### REDIS ####
  redis:
    image: 'redis:latest'

  ### FRONTEND ####
  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
    - "8080:3000"

  #### GATEWAY ####
#  gateway:
#    restart: always
#    build:
#      context: ./backend/gateway
#      dockerfile: Dockerfile
#    depends_on:
#    - eureka

  #### EUREKA ####
#  eureka:
#    restart: always
#    build:
#      context: ./backend/eureka
#      dockerfile: Dockerfile

  #### MICROSERVICES ####
  #auth:
  #  build:
  #    context: ./backend/user-details
  #    dockerfile: Dockerfile
  #  depends_on:
  #  - gateway
  #  - auth-db

  payment:
    build:
      context: ./backend/payment
      dockerfile: Dockerfile
    ports:
    - "8084:9091"
    depends_on:
#    - gateway
    - payment-db
#    - auth

  booking:
    build:
      context: ./backend/booking
      dockerfile: Dockerfile
    ports:
    - "8083:9091"
    depends_on:
#    - gateway
    - booking-db
    - payment
  #  - auth

  movies:
    build:
      context: ./backend/movies
      dockerfile: Dockerfile
    ports:
    - "8082:9091"
    depends_on:
#    - gateway
    - movies-db

  venues_0:
    build:
      context: ./backend/venues
      dockerfile: Dockerfile
    ports:
    - "8087:9091"
    depends_on:
#    - gateway
    - venues-db

  venues_1:
    build:
      context: ./backend/venues
      dockerfile: Dockerfile
    ports:
      - "8081:9091"
    depends_on:
#    - gateway
    - venues-db

  events:
    build:
      context: ./backend/events
      dockerfile: Dockerfile
    ports:
      - "8085:9091"
    depends_on:
#    - gateway
    - events-db
