version: '3.3'

services:

  ### GATEWAY ###
  gateway:
    build:
      context: ./backend/gateway
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    depends_on:
        - eureka

  ### EUREKA ####
  eureka:
    build:
      context: ./backend/eureka
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  booking-db:
    image: 'postgres:latest'

  #### RABBITMQ ####
  rabbitmq:
    image: "rabbitmq:3"


  booking:
    build:
      context: ./backend/booking
      dockerfile: Dockerfile
    depends_on:
    - gateway
    - booking-db
    - rabbitmq

