version: '3.3'

services:
  rabbitmq:
      image:  "rabbitmq:3"

  booking-db:
      image: "postgres:10"

  payment-db:
      image: "postgres:10"

  sender:
    build:
        context: ./payment
        dockerfile: Dockerfile
    ports:
       - "9000:8080"
    depends_on:
       - rabbitmq
       - payment-db

  receiver_0:
     build:
        context: ./booking
        dockerfile: Dockerfile
     ports:
        - "9001:8080"
     depends_on:
        - rabbitmq
        - booking-db
