spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: service
        uri: lb://service
        predicates:
        - Path=/service/**
        filters:
        - StripPrefix=1
      - id: movies
        uri: lb://movies
        predicates:
        - Path=/movies-service/**
        filters:
        - StripPrefix=1
      - id: venues
        uri: lb://venues
        predicates:
        - Path=/venues-service/**
        filters:
        - StripPrefix=1

eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
