spring:
  application:
    name: gateway
  session:
    store-type: none
  redis:
    host: redis
    port: 6379

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
            - GET
      discovery:
        locator:
          enabled: true

      routes:
#      - id: movies
#        uri: lb://movies
#        predicates:
#        - Path=/api/movies/**
#        filters:
#        - StripPrefix=1
#
#      - id: venues
#        uri: http://venues:8080
#        predicates:
#        - Path=/api/venues/**
#        filters:
#        - StripPrefix=1
#
#      - id: payment
#        uri: lb://payment
#        predicates:
#        - Path=/api/payments/**
#        filters:
#        - StripPrefix=1
#
#      - id: events
#        uri: lb://events
#        predicates:
#        - Path=/graphql
#        filters:
#        - StripPrefix=1

      - id: booking
        uri: lb://booking
        predicates:
        - Path=/booking-service/**
        filters:
        - StripPrefix=1

#      - id: auth
#        uri: lb://auth
#        predicates:
#        - Path=/api/auth/**
#        filters:
#        - StripPrefix=1

#      - id: frontend
#        uri: http://frontend:3000
#        predicates:
#        - Path=/**

eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/


