spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: bookings
        uri: lb://bookings
        predicates:
        - Path=/booking-service/**
        filters:
        - StripPrefix=1
      - id: movies
        uri: lb://movies
        predicates:
        - Path=/movies-service/**
        filters:
        - StripPrefix=1
      - id: venues-server
        uri: lb://venues-server
        predicates:
        - Path=/venues-service/**
        filters:
        - StripPrefix=1
      - id: events
        uri: lb://events
        predicates:
        - Path=/events-service/**
        filters:
        - StripPrefix=1
      - id: payment
        uri: lb://payment
        predicates:
        - Path=/payment-service/**
        filters:
        - StripPrefix=1
      - id: frontend
        uri: http://frontend
        predicates:
        - Path=/**

eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
