spring:
  application:
    name: venues

  datasource:
    url: "jdbc:postgresql://venues-db:5432/postgres"
    username: "postgres"
    password: ""
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.PostgreSQL9Dialect
    properties.hibernate.temp.use_jdbc_metadata_defaults: false

server:
  port: 9091

eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/