spring:
  session:
    store-type: redis
  redis:
      host: redis
      port: 6379
  datasource:
      url: "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1"
      driver-class-name: "org.h2.Driver"
  jpa:
      database: "h2"
      hibernate:
        ddl-auto: "create-drop"
      show-sql: true

logging:
  level:
    org.springframework.security: debug

server:
  port: 9091