# From Andrea's repository.
spring:
 session:
   # during testing for this service in isolation,
   # do not use Redis. Disabling SpringSession will fall-back to
   # default sessions in the servlet
   store-type: none
 datasource:
   url: "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1"
   driver-class-name: "org.h2.Driver"
 jpa:
   database: "h2"
   hibernate:
     ddl-auto: "create-drop"
   show-sql: false
logging:
 level:
   org: ERROR