server:
  port: 8761

eureka:
  instance:
    hostname: eureka
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZowne: http://${eureka.instance.hostname}:${server.port}/eureka/