server:
  port: 8761

eureka:
  instance:
    hostname: eureka
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  level:
    com:
      netflix:
        loadbalancer: debug



