server:
  port: 8761

# when running from Docker Compose, need to change from "localhost" to "eureka" host name

eureka:
  instance:
    hostname: eureka
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/