spring:
  application:
    name: events
  datasource:
    url: "jdbc:h2:mem:"
    driver-class-name: "org.h2.Driver"
server:
  port: 8083

fixerMoviesWebAddress: api.fixer.io:80
fixerVenuesWebAddress: api.fixer.io:80