spring:
  application:
    name: events
  datasource:
    url: "jdbc:postgresql://events-postgres:5432/postgres"
    username: "postgres"
    password: ""
    driver-class-name: "org.postgresql.Driver"
    jpa:
      database: "postgresql"
      hibernate:
        ddl-auto: "update"

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
graphiql:
  mapping: /graphiql
  endpoint:
    graphql: /events-service/graphql
  enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

fixerMoviesWebAddress: movies
fixerVenuesWebAddress: venues-server