spring:
  application:
    name: payment
  datasource:
    url: "jdbc:postgresql://payment-db:5432/postgres"
    username: "postgres"
    password: ""
    driver-class-name: "org.postgresql.Driver"
  jpa:
    show-sql: true
    database: "postgresql"
    hibernate:
      ddl-auto: update
   properties.hibernate.temp.use_jdbc_metadata_defaults: false

server:
  port: 9091