# Configuring here to use an actual database, whose IP address depends
# on where Docker Compose starts it

spring:
  application:
    name: booking
  datasource:
    url: "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1"
    driver-class-name: "org.h2.Driver"
  jpa:
    database: "h2"
    hibernate:
      ddl-auto: "create-drop"
    show-sql: true

eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

