server:
  port: 9091

spring:
  application:
    name: booking
  datasource:
    url: "jdbc:postgresql://booking-db:5432/postgres"
    username: "postgres"
    password: ""
    driver-class-name: "org.postgresql.Driver"
  jpa:
    show-sql: true
    database: "postgresql"
    hibernate:
      ddl-auto: update

eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/