spring:
  application:
    name: booking

  datasource:
    url: "jdbc:postgresql://booking-db:5432/postgres"
    username: "postgres"
    password: ""
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: rabbitmq
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.PostgreSQL9Dialect
    properties.hibernate.temp.use_jdbc_metadata_defaults: false

server:
  port: 9091
#
#eureka:
#  instance:
#    preferIpAddress: true
#  client:
#    healthcheck:
#      enabled: true
#    serviceUrl:
#      defaultZone: http://eureka:8761/eureka/