spring:
  application:
    name: booking
  datasource:
    url: "jdbc:h2:mem:"
    driver-class-name: "org.h2.Driver"
  jpa:
    database: "postgresql"
    hibernate:
      ddl-auto: "update"
  rabbitmq:
    host: rabbitmq
