spring:
  application:
    name: bookings
  session:
    store-type: none
  datasource:
    url: "jdbc:postgresql://bookings-postgres:5432/postgres"
    username: "postgres"
    password: ""
    driver-class-name: "org.postgresql.Driver"
    jpa:
      database: "postgresql"
      hibernate:
        ddl-auto: "update"

logging:
  level:
    org: ERROR

eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

