export const movieList = [
	{
		vote_count: 1367,
		id: 335983,
		trailer: false,
		vote_average: 6.6,
		title: 'Venom',
		popularity: 283.853,
		poster: '/2uNW4WbgBXL25BAbXGLnLqX71Sw.jpg',
		genres: [878, 28, 35, 80],
		coverArt: '/VuukZLgaCrho2Ar8Scl9HtV3yD.jpg',
		overview:
			'When Eddie Brock acquires the powers of a symbiote, he will have to release his alter-ego “Venom” to save his life.',
		releaseDate: '2018-10-03',
	},
	{
		vote_count: 783,
		id: 332562,
		trailer: false,
		vote_average: 7.6,
		title: 'A Star Is Born',
		popularity: 235.607,
		poster: '/wrFpXMNBRj2PBiN4Z5kix51XaIZ.jpg',
		original_language: 'en',
		original_title: 'A Star Is Born',
		genres: [18, 10402, 10749],
		coverArt: '/840rbblaLc4SVxm8gF3DNdJ0YAE.jpg',
		adult: false,
		overview:
			"Seasoned musician Jackson Maine discovers—and falls in love with—struggling artist Ally. She has just about given up on her dream to make it big as a singer—until Jack coaxes her into the spotlight. But even as Ally's career takes off, the personal side of their relationship is breaking down, as Jack fights an ongoing battle with his own internal demons.",
		releaseDate: '2018-10-03',
	},
	{
		vote_count: 605,
		id: 346910,
		trailer: false,
		vote_average: 5.4,
		title: 'The Predator',
		popularity: 196.703,
		poster: '/wMq9kQXTeQCHUZOG4fAe5cAxyUA.jpg',
		original_language: 'en',
		original_title: 'The Predator',
		genres: [27, 878, 28, 53],
		coverArt: '/f4E0ocYeToEuXvczZv6QArrMDJ.jpg',
		adult: false,
		overview:
			'From the outer reaches of space to the small-town streets of suburbia, the hunt comes home. Now, the universe’s most lethal hunters are stronger, smarter and deadlier than ever before, having genetically upgraded themselves with DNA from other species. When a young boy accidentally triggers their return to Earth, only a ragtag crew of ex-soldiers and a disgruntled science teacher can prevent the end of the human race.',
		releaseDate: '2018-09-13',
	},
	{
		vote_count: 183,
		id: 369972,
		trailer: false,
		vote_average: 7,
		title: 'First Man',
		popularity: 164.747,
		poster: '/i91mfvFcPPlaegcbOyjGgiWfZzh.jpg',
		original_language: 'en',
		original_title: 'First Man',
		genres: [36, 18],
		coverArt: '/z1FkoHO7bz40S4JiptWHSYoPpxq.jpg',
		adult: false,
		overview:
			'A look at the life of the astronaut, Neil Armstrong, and the legendary space mission that led him to become the first man to walk on the Moon on July 20, 1969.',
		releaseDate: '2018-10-11',
	},
	{
		vote_count: 1149,
		id: 439079,
		trailer: false,
		vote_average: 5.8,
		title: 'The Nun',
		popularity: 149.009,
		poster: '/sFC1ElvoKGdHJIWRpNB3xWJ9lJA.jpg',
		original_language: 'en',
		original_title: 'The Nun',
		genres: [27, 9648, 53],
		coverArt: '/fgsHxz21B27hOOqQBiw9L6yWcM7.jpg',
		adult: false,
		overview:
			'When a young nun at a cloistered abbey in Romania takes her own life, a priest with a haunted past and a novitiate on the threshold of her final vows are sent by the Vatican to investigate. Together they uncover the order’s unholy secret. Risking not only their lives but their faith and their very souls, they confront a malevolent force in the form of the same demonic nun that first terrorized audiences in “The Conjuring 2,” as the abbey becomes a horrific battleground between the living and the damned.',
		releaseDate: '2018-09-05',
	},
	{
		vote_count: 177,
		id: 463272,
		trailer: false,
		vote_average: 6.4,
		title: 'Johnny English Strikes Again',
		popularity: 134.308,
		poster: '/tCBxnZwLiY1BOKw3tH6AxHZdqPh.jpg',
		original_language: 'en',
		original_title: 'Johnny English Strikes Again',
		genres: [12, 10751, 28, 35],
		coverArt: '/yCOLqh5MOGyYdo58Ap0aWvKop9h.jpg',
		adult: false,
		overview:
			'Disaster strikes when a criminal mastermind reveals the identities of all active undercover agents in Britain. The secret service can now rely on only one man—Johnny English. Currently teaching at a minor prep school, Johnny springs back into action to find the mysterious hacker. For this mission to succeed, he’ll need all of his skills—what few he has—as the man with yesterday’s analogue methods faces off against tomorrow’s digital technology.',
		releaseDate: '2018-09-13',
	},
	{
		vote_count: 82,
		id: 424139,
		trailer: false,
		vote_average: 6.4,
		title: 'Halloween',
		popularity: 111.754,
		poster: '/lNkDYKmrVem1J0aAfCnQlJOCKnT.jpg',
		original_language: 'en',
		original_title: 'Halloween',
		genres: [27],
		coverArt: '/hO1oTBGNxO5fBKVEuWnSpICJH7c.jpg',
		adult: false,
		overview:
			'Laurie Strode comes to her final confrontation with Michael Myers, the masked figure who has haunted her since she narrowly escaped his killing spree on Halloween night four decades ago.',
		releaseDate: '2018-10-18',
	},
	{
		vote_count: 21,
		id: 442062,
		trailer: false,
		vote_average: 6.1,
		title: 'Goosebumps 2: Haunted Halloween',
		popularity: 106.506,
		poster: '/8bcpki9GfXdXj9esFpPtlate8v0.jpg',
		original_language: 'en',
		original_title: 'Goosebumps 2: Haunted Halloween',
		genres: [12, 35, 14, 27, 10751],
		coverArt: '/9xYg9ScjGaO2HrLfOfYZirTrB3o.jpg',
		adult: false,
		overview:
			'Two boys face an onslaught from witches, monsters, ghouls and a talking dummy after they discover a mysterious book by author R. L. Stine.',
		releaseDate: '2018-10-11',
	},
	{
		vote_count: 98,
		id: 446894,
		trailer: false,
		vote_average: 6.5,
		title: 'Smallfoot',
		popularity: 105.326,
		poster: '/4nKoB6wMVXfsYgRZK5lHZ5VMQ6J.jpg',
		original_language: 'en',
		original_title: 'Smallfoot',
		genres: [35, 16, 10751, 12, 14],
		coverArt: '/7t88SoT3Dd8DhGnQuVoSbMNUl3W.jpg',
		adult: false,
		overview:
			"A bright young yeti finds something he thought didn't exist—a human. News of this “smallfoot” throws the simple yeti community into an uproar over what else might be out there in the big world beyond their snowy village.",
		releaseDate: '2018-09-20',
	},
	{
		vote_count: 127,
		id: 347375,
		trailer: false,
		vote_average: 5.4,
		title: 'Mile 22',
		popularity: 99.43,
		poster: '/dT1XzjxRDR56xOm4Ph0INV4EmWJ.jpg',
		original_language: 'en',
		original_title: 'Mile 22',
		genres: [28],
		coverArt: '/eTwftrInxzZTSLUkX5hoifOczKJ.jpg',
		adult: false,
		overview:
			'A CIA field officer and an Indonesian police officer are forced to work together in confronting political corruption. An informant must be moved twenty-two miles to safety.',
		releaseDate: '2018-08-16',
	},
	{
		vote_count: 1040,
		id: 447200,
		trailer: false,
		vote_average: 6.1,
		title: 'Skyscraper',
		popularity: 94.371,
		poster: '/5LYSsOPzuP13201qSzMjNxi8FxN.jpg',
		original_language: 'en',
		original_title: 'Skyscraper',
		genres: [28, 53, 18],
		coverArt: '/oMKFQmoVgB69fyXfSMu0lGlHJP2.jpg',
		adult: false,
		overview:
			"Framed and on the run, a former FBI agent must save his family from a blazing fire in the world's tallest building.",
		releaseDate: '2018-07-11',
	},
	{
		vote_count: 206,
		id: 439015,
		trailer: false,
		vote_average: 4.4,
		title: 'Slender Man',
		popularity: 88.447,
		poster: '/huSncs4RyvQDBmHjBBYHSBYJbSJ.jpg',
		original_language: 'en',
		original_title: 'Slender Man',
		genres: [9648, 53],
		coverArt: '/5K0fgMaJSdEvqSsS8e3Ez4TpvXR.jpg',
		adult: false,
		overview:
			'In a small town in Massachusetts, four high school girls perform a ritual in an attempt to debunk the lore of Slender Man. When one of the girls goes mysteriously missing, they begin to suspect that she is, in fact, his latest victim.',
		releaseDate: '2018-08-10',
	},
	{
		vote_count: 85,
		id: 446021,
		trailer: false,
		vote_average: 6.5,
		title: 'Bad Times at the El Royale',
		popularity: 76.839,
		poster: '/iNtFgXqXPRMkm1QO8CHn5sHfUgE.jpg',
		original_language: 'en',
		original_title: 'Bad Times at the El Royale',
		genres: [53, 80, 9648],
		coverArt: '/gb3TVVZNNxVGNfS1NxGaiWZfwnW.jpg',
		adult: false,
		overview:
			"Seven strangers, each with a secret to bury, meet at Lake Tahoe's El Royale, a rundown hotel with a dark past in 1969. Over the course of one fateful night, everyone will have a last shot at redemption.",
		releaseDate: '2018-10-04',
	},
	{
		vote_count: 850,
		id: 400155,
		trailer: false,
		vote_average: 6.8,
		title: 'Hotel Transylvania 3: Summer Vacation',
		popularity: 75.365,
		poster: '/gjAFM4xhA5vyLxxKMz38ujlUfDL.jpg',
		original_language: 'en',
		original_title: 'Hotel Transylvania 3: Summer Vacation',
		genres: [10751, 14, 35, 16],
		coverArt: '/m03jul0YdVEOFXEQVUv6pOVQYGL.jpg',
		adult: false,
		overview:
			'Dracula, Mavis, Johnny and the rest of the Drac Pack take a vacation on a luxury Monster Cruise Ship, where Dracula falls in love with the ship’s captain, Ericka, who’s secretly a descendant of Abraham Van Helsing, the notorious monster slayer.',
		releaseDate: '2018-06-28',
	},
	{
		vote_count: 685,
		id: 345887,
		trailer: false,
		vote_average: 6.2,
		title: 'The Equalizer 2',
		popularity: 75.226,
		poster: '/cQvc9N6JiMVKqol3wcYrGshsIdZ.jpg',
		original_language: 'en',
		original_title: 'The Equalizer 2',
		genres: [53, 28, 80],
		coverArt: '/z6KLDE72SxE1A8JcJTmmnWArOvR.jpg',
		adult: false,
		overview:
			'Robert McCall returns to deliver his special brand of vigilante justice—but how far will he go when it’s someone he loves?',
		releaseDate: '2018-07-19',
	},
	{
		vote_count: 293,
		id: 399360,
		trailer: false,
		vote_average: 5.3,
		title: 'Alpha',
		popularity: 71.449,
		poster: '/afdZAIcAQscziqVtsEoh2PwsYTW.jpg',
		original_language: 'en',
		original_title: 'Alpha',
		genres: [12, 18],
		coverArt: '/nKMeTdm72LQ756Eq20uTjF1zDXu.jpg',
		adult: false,
		overview:
			'After a hunting expedition goes awry, a young caveman struggles against the elements to find his way home.',
		releaseDate: '2018-08-17',
	},
	{
		vote_count: 24,
		id: 438808,
		trailer: false,
		vote_average: 5.6,
		title: 'White Boy Rick',
		popularity: 68.481,
		poster: '/376lzYd3vE04qBA5Js93UAKrnvj.jpg',
		original_language: 'en',
		original_title: 'White Boy Rick',
		genres: [18, 80],
		coverArt: '/4Y0eLVkUwThX9pt1uqVoWoCtvcl.jpg',
		adult: false,
		overview:
			'The story of teenager, Richard Wershe Jr., who became an undercover informant for the police during the 1980s and was ultimately arrested for drug-trafficking and sentenced to life in prison.',
		releaseDate: '2018-09-14',
	},
	{
		vote_count: 3,
		id: 523873,
		trailer: false,
		vote_average: 3.5,
		title: 'Kung Fu League',
		popularity: 62.079,
		poster: '/rW0A73hjzPWVwADlCTLnjLhAFLX.jpg',
		original_language: 'zh',
		original_title: '功夫联盟',
		genres: [28, 35],
		coverArt: null,
		adult: false,
		overview:
			'Martial arts comedy following a group of kung fu legends banding together to take on the bad guys. The legends includes VINCENT ZHAO reprising his role as ‘Wong Fei Hung’ with DENNIS TO once again portraying ‘Wing Chun’ master ‘Ip Man’, DANNY CHAN KWOK KWAN as ‘Chen Zhen’ and ANDY ON as master ‘Huo Yuan Jia’.',
		releaseDate: '2018-10-19',
	},
];
